trigger:

- main

pool:
 vmImage: ubuntu-latest

steps:
- task: CmdLine@2
 inputs:
   script: 'docker build . -t $(imageName):$(Build.BuildNumber)'
 displayName: dockerBuild

- task: prisma-cloud-compute-scan@3
 displayName: prismaCloudScan
 inputs:
   twistlockService: '$(scPrismaCloudConsole)'
   artifact: '$(imageName):$(Build.BuildNumber)'