trigger:

- main

pool:
 vmImage: ubuntu-latest

steps:
- task: prisma-cloud-compute-scan@3
 displayName: prismaCloudScan
 inputs:
   scanType: 'serverless'
   twistlockService: '$(scPrismaCloudConsole)'
   artifact: '$(functionName)'