pool:
  vmImage: ubuntu-latest

steps:
- task: Palo-Alto-Networks.build-release-task.custom-build-release-task.prisma-cloud-compute-scan@3
  displayName: 'Prisma Cloud Serverless Scan'
  inputs:
    scanType: images
    twistlockService: '<SERVICE_CONNECTION_NAME>' # The Service Connection name you created to connect to Prisma Clou Compute
    artifact: 'davidaavilar/bwapp' # The image you want to scan
  enabled: true
  continueOnError: false